// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRgVgl6FDt6kfq9lx7dys5a2Nl3ZR8Qc',
    appId: '1:729729573631:web:efab1146be4cb500f3e2ca',
    messagingSenderId: '729729573631',
    projectId: 'appointment-booking-firebase',
    authDomain: 'appointment-booking-firebase.firebaseapp.com',
    storageBucket: 'vc-appointment-booking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHd1oTdIPnTTYlUVnm3JboXhy_QRFTtI',
    appId: '1:729729573631:android:0cb574f527d5a093f3e2ca',
    messagingSenderId: '729729573631',
    projectId: 'appointment-booking-firebase',
    storageBucket: 'vc-appointment-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdXZBLjwwlwApaHfbVuSEopI67wblwC_E',
    appId: '1:729729573631:ios:ba13421c92f39b95f3e2ca',
    messagingSenderId: '729729573631',
    projectId: 'appointment-booking-firebase',
    storageBucket: 'vc-appointment-booking.firebasestorage.app',
    iosBundleId: 'com.example.vcAppointmentBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdXZBLjwwlwApaHfbVuSEopI67wblwC_E',
    appId: '1:729729573631:ios:ba13421c92f39b95f3e2ca',
    messagingSenderId: '729729573631',
    projectId: 'appointment-booking-firebase',
    storageBucket: 'vc-appointment-booking.firebasestorage.app',
    iosBundleId: 'com.example.vcAppointmentBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRgVgl6FDt6kfq9lx7dys5a2Nl3ZR8Qc',
    appId: '1:729729573631:web:1281568e3cd5ad30f3e2ca',
    messagingSenderId: '729729573631',
    projectId: 'appointment-booking-firebase',
    authDomain: 'appointment-booking-firebase.firebaseapp.com',
    storageBucket: 'vc-appointment-booking.firebasestorage.app',
  );
}
